apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-keycloak
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-theme
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi