apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - image: quay.io/keycloak/keycloak:8.0.2
          imagePullPolicy: IfNotPresent
          name: keycloak
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_USER
              value: "fake"
            - name: KEYCLOAK_PASSWORD
              value: "fakepassword"
           