# Generated by Django 3.2 on 2022-11-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aithsh',
            name='formFile',
        ),
    ]
