# Generated by Django 3.2 on 2022-11-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_remove_aithsh_formfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='aithsh',
            name='age',
            field=models.CharField(default=18, max_length=255),
            preserve_default=False,
        ),
    ]
