# Generated by Django 3.2 on 2022-11-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_diakoph_formfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apografh',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=255)),
                ('AFM', models.CharField(max_length=255)),
                ('nomos', models.CharField(max_length=255)),
                ('perioxh', models.CharField(max_length=255)),
                ('odos', models.CharField(max_length=255)),
                ('aithsh_id', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('katatajh', models.CharField(max_length=255)),
                ('education_level', models.CharField(max_length=255)),
                ('communication', models.CharField(max_length=255)),
                ('formFile', models.FileField(default='0000000', upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
