# Generated by Django 3.2 on 2022-11-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_auto_20221110_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='apografh',
            name='status',
            field=models.CharField(default='Unchecked', max_length=255),
            preserve_default=False,
        ),
    ]
