# Generated by Django 3.2 on 2022-11-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_apografh_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyRoles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('useremail', models.CharField(max_length=255)),
                ('userrole', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
